# Provision AWS RDS
Parameters:
  RDSUserAdmin:
    Type: String
    Default: RDS.User.Admin
  UserAdmin:
    Type: String
    Default: DB_Admin

#iam user
Resources:
  RUserAdmin:
    Type: AWS::IAM::User
    Properties: 
      Path: "/"
      LoginProfile:
        Password: myP@ssW0rd
      UserName: RDS.User.Admin
      Policies:
        - PolicyName: PolicyRDSConnect
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ["rds-db:connect"]
                Resource: ["Fn::Join" : ["",['arn:aws:rds-db:', !Ref "AWS::Region",':',!Ref "AWS::AccountId",':dbuser:*/',!Ref UserAdmin]]]
        - PolicyName: PolicyRDSFullAccesses
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ["rds-db:*"]
                Resource: "*"
  RAccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      UserName: !Ref RUserAdmin
  RVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: '10.41.0.0/16'
      Tags:
        - Key: Name
          Value: RDS-VPC
  RSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        "Fn::Join" : ['',[!Ref "AWS::Region",'a']]
      CidrBlock: '10.41.1.0/24'
      VpcId: !Ref RVPC
      Tags:
        - Key: Name
          Value: 
            "Fn::Join" : ["",[!Ref "AWS::Region",'a']]
  RSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        "Fn::Join" : ['',[!Ref "AWS::Region",'b']]
      CidrBlock: '10.41.2.0/24'
      VpcId: !Ref RVPC
      Tags:
        - Key: Name
          Value: 
            "Fn::Join" : ["",[!Ref "AWS::Region",'b']]
  RSubnet03:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        "Fn::Join" : ['',[!Ref "AWS::Region",'c']]
      CidrBlock: '10.41.3.0/24'
      VpcId: !Ref RVPC
      Tags:
        - Key: Name
          Value: 
            "Fn::Join" : ["",[!Ref "AWS::Region",'c']]

Outputs:
  MyStacksRegion:
    Value: !Ref AWS::Region        
  MyStacksRDSUserAdmin:
    Value: !Ref UserAdmin
  MyStacksAccessKey:
    Value: !Ref "RAccessKey"
  MyStacksSecretAccessKey:
    Value: 
      "Fn::GetAtt" : ["RAccessKey","SecretAccessKey"]

#add VPC
#add VPC peering
#add 3 subnet
#add internet gateway
#add route table for default
#add route table for internet gateway
#add aws security group
#add rds node
#add rds_parameter
#add parameter group
